### ISSUE TITLE
peptidyl-diphthamide biosynthetic process from peptidyl-histidine

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13565]
Def
The modification of peptidyl-histidine to 2'-(3-carboxamido-3-(trimethylammonio)propyl)-L-histidine, known as diphthamide, found in translation elongation factor EF-2. The process occurs in eukaryotes and archaea but not eubacteria.

Is this modification is specifically involved in regulation of cytoplasmic translational initiation ?
If so can it have a parent (would bring genes annotated to his process into slims)

**Comment by hdrabkin** [comment]
Need a reference to begin with  8-)

**Comment by hdrabkin** [comment]
maybe this helps for linking to the regulation of fidelity (but not initiation)

"Diphthamide modification on eukaryotic elongation factor 2 is needed to assure fidelity of mRNA
translation and mouse development"

**Comment by ValWood** [comment]
OK in that case maybe "regulation of elongation" not initiation!

Presumably the ref used to create  def the term would do it?

**Comment by hdrabkin** [comment]
Am confused; the term is already there. You just want an additional parent (regulation of translational elongation?).

**Comment by ValWood** [comment]
That's correct.


peptidyl-diphthamide biosynthetic process is really a function/modification, it doesn't really describe the role.
The role is regulating translation. It doesn't really make sense to have 

"peptidyl-diphthamide biosynthetic process"  and "regulation of translation elongation" concurrent annotations to describe the same process.

If the parent is added, all will be annotated to  "regulation of translation elongation"  without any reannotation, and this gene product will be captured by most slims. (Most slims do not have "protein modification" as a classification for obvious reasons.

v

**Comment by hdrabkin** [comment]
done

**Comment by ValWood** [comment]
Sorry Harold, could you make this parent 

"regulation of cytoplasmic translational elongation" instead of "regulation of translational elongation"? It still isn't slimming into the correct bin...

thanks

val

**Comment by hdrabkin** [comment]
done
