### ISSUE TITLE
NTR: GO terms for kinetoplastid ciliary components

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#14713]
[Term]
id: ##########
name: flagella connector
namespace: cellular_component
def: "A mobile transmembrane junction at the tip of the flagellum of some kinetoplastid species linking the tip of a new growing flagellum to an older flagellum"
comment: Note that cilia and eukaryotic flagella are deemed to be equivalent.
is_a: GO:0044441 ! ciliary part
PMID:11641501, PMID:15075226, PMID:16954145, PMID:26820516

[Term]
id: ##########
name: flagellum attachment zone
namespace: cellular_component
def: "A network of cytoskeletal and membranous connections responsible for the lateral attachment of the cilium to the cell body in some trypanosomatid species"
comment: Note that cilia and eukaryotic flagella are deemed to be equivalent.
synonym: FAZ
is_a: GO:0044441 ! ciliary part
is_a: GO:0044430 ! cytoskeletal part
is_a: GO:0070161 ! anchoring junction
relationship: part_of GO:0097014 ! ciliary cytoplasm
relationship: part_of GO:0030863 ! cortical cytoskeleton
PMID:2606941, PMID:10361731, PMID:16414276, PMID:17945531, PMID:20541452, PMID:25972344, PMID:26746239, PMID:26776656 

[Term]
id: ##########
name: bilobe structure
namespace: cellular_component
def: "A cytoskeletal structure in some kinetoplastid species linking the structures of the ciliary pocket collar and the cilium attachment zone"
is_a: GO:0044430 ! cytoskeletal part
intersection_of: GO:1990900 ! ciliary pocket collar
intersection_of: ########## ! flagellum attachment zone
PMID:22327007, PMID:22445359, PMID:26540076

[Term]
id: ##########
name: tripartite attachment complex
namespace: cellular_component
def: "A three-part cytoskeletal structure in kinetoplastid species linking mitochondrial DNA organised in a kinetoplast through the mitochondrial membranes to the basal body"
is_a: GO:0044430 ! cytoskeletal part
is_a: GO:0044429 ! mitochondrial part
PMID:12802053, PMID:18059470, PMID:24821793, PMID:27168148

[Term]
name: ciliary pro-basal body
namespace: cellular_component
def: "The cilary pro-basal body is an immature form of the ciliary basal body found next to the basal body of many cilia. Pro-basal bodies do not nucleate a cilium, but may become modified and 'mature' into a basal body which then nucleates a cilium"
comment: The pro-basal body is the structure similar to a 'ciliary basal body' (GO:0036064) or 'centriole' (GO:0005814) often found next to the 'ciliary basal body' (GO:0036064) of a cilium. Pro-basal bodies are distinct from basal bodies as they are not at the base of a cilium, but may nucleate a cilium in future ciliogenesis. While 'immature' they may contain proteins unique to this state. Note that cilia and eukaryotic flagella are deemed to be equivalent.
synonym: "flagellar pro-basal body" EXACT []
synonym: "pro-basal body" BROAD []
synonym: "pro-centriole" BROAD []
is_a: GO:0005815 ! microtubule organizing center
intersection_of: GO:0005815 ! microtubule organizing center
PMID:26862392, PMID:28049148

**Comment by krchristie** [comment]
Hi @Achchuthan 

I have some questions for you.

1. Regarding the term "flagella connector", do you feel this is really a part of the cilium? The newer papers you list seem to describe the FC as a transmembrane connector, but not necessarily, as far as I can see, a part of the cilium/flagellum itself. I can make it both, but want to confirm that people really think the FC is a part of the cilium, rather than a junction that spans between two flagella, but isn't part of either.

2. These terms seem like they might need to have a taxon restriction to indicate that they are only in certain organisms. Is Trypanosoma broad enough? or would it need to be broader like Kinetoplastida?

Trypanosoma: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=5690
Kinetoplastida: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=5653

Perhaps more questions to come, but I'll start with these two.

**Comment by paolaroncaglia** [comment]
@krchristie 
FYI, some background info provided by the submitter by email:
"I am working as a curator with GeneDB/ EuPathDB databases. Fatima Silva, another curator with GeneDB/ EuPathDB contacted you some time ago regarding the submission of new term requests to GO consortium for kinetoplastid specific ciliary components. Fatima Silva has recently left the project and I have taken over the curation of Kinetoplastida species from her."

**Comment by krchristie** [comment]
Thanks @paolaroncaglia

**Comment by Achchuthan** [comment]
Hi @krchristie

Thanks a lot for you feedback and questions.

1. You are right in pointing out that Flagella connector is a mobile transmembrane junction that spans between two flagella and hence it is not necessarily a part of either flagella. I agree with not annotating FC as a ciliary part. However, this is a specific transmembrane connector that grows from the distal tip of new flagellum to the old flagellum and hence the name should reflect this function. I would prefer the term “flagellar connector” as described in these publications.

2. The flagella, flagellar pocket and flagellar attachment zone are all features that are also present in other Kinetoplastids such as Crithedia and Leishmania. Therefore, the taxonomic restriction should be broader to accommodate all Kinetoplastida.

Thanks again.

Best wishes,
Achchuthan

**Comment by krchristie** [comment]
@Achchuthan - Thanks very much for answering my previous questions. That's very helpful information.

I'm adding these four terms now, with modifications as indicated below:

**name: flagella connector**
is_a: GO:0044441 ! ciliary part `As discussed, did not use this is_a parent. Chose 'cell junction' instead. I was wondering about whether it should be 'anchoring junction' instead, but wasn't really sure if this counted as a junction between a cell and extracellular matrix, so went more general. Let me know if you feel the more specific 'anchoring junction' is appropriate.`

**name: flagellum attachment zone**
is_a: GO:0044441 ! ciliary part `again, I think this is a structure that attaches to the cilium/flagellum, but not part of it; did not add`
is_a: GO:0044430 ! cytoskeletal part `From the def and one of the 2016 Trends in Parasitology review, it seems to me that parts of the FAZ are cytoskeletal parts, but it didn't seem like ALL of it was cytoskeletal, so I did not add this relationship`
is_a: GO:0070161 ! anchoring junction `used this relationship`
relationship: part_of GO:0097014 ! ciliary cytoplasm `From the def and one of the 2016 Trends in Parasitology review, it does not seem to me that ALL of the FAZ is part of the 'ciliary cytoplasm', so I did not add this relationship`
relationship: part_of GO:0030863 ! cortical cytoskeleton `From the def and one of the 2016 Trends in Parasitology review, it seems to me that parts of the FAZ are cytoskeletal parts, but it didn't seem like ALL of it was cytoskeletal, so I did not add this relationship`

**name: bilobe structure**
def: "A cytoskeletal structure in some kinetoplastid species linking the structures of the ciliary pocket collar and the cilium attachment zone"
is_a: GO:0044430 ! cytoskeletal part
intersection_of: GO:1990900 ! ciliary pocket collar `intersection_of is meant for specific types of logical definitions, not to indicate this kind of adjacency of a structure; not added`
intersection_of: ########## ! flagellum attachment zone `also not added`
synonym (EXACT): "kinetoplastid flagellar hook complex"  [PMID:26540076] `I thought this synonym, based on the cited PMID, would be useful to add also.`

**name: tripartite attachment complex**
is_a: GO:0044430 ! cytoskeletal part
is_a: GO:0044429 ! mitochondrial part `being a structure between the basal body and the mitochondrion, I don't think this can be a 'mitochondrial part'; did not add`
synonym (RELATED): TAC

**Comment**: `When a comment on the equivalence of cilia and flagella in euks was needed, I have used the form present in existing terms in the ontology: 
> "Note that we deem cilium and microtubule-based flagellum to be equivalent; the primary term name reflects frequency of use." 

Things still to do:

- [ ] This 5th term, **name: ciliary pro-basal body** requires some thought. It seems equivalent to another term I would want, i.e. daughter centriole, but that we do not have. I have previously wanted to be able to annotate the mother or daughter specifically, so I see the argument to have this term. However, I want to make sure we do it in a coherent way for centrioles and basal bodies, which are essentially the same thing, depending on what aspect of the cell cycle or ciliation a researcher focuses on.

- [ ] add Kinetoplastic taxon to included IDs so I can add the taxon constraint for appropriate terms

**Comment by Achchuthan** [comment]
Hi @krchristie,

Thanks a lot for your kind help with adding these terms to the GO. 

Regarding "flagella connector", I would also choose a more general term such as "cell junction" as the parent rather than "anchoring junction" as I don't think this connection will count as a connection between a cell and extracellular matrix. 

Removing the "ciliary part" parent term from the annotations of "flagellar connector" and "flagellar attachment zone" terms also makes sense.

Many thanks for deciding to work further on "daughter centriole" and "basal body" related terms.

Best wishes,
Achchuthan

**Comment by krchristie** [comment]
@cmungall - Is there something else I need to do to be able to use this new taxon ID?  You can see from the text below, copied from my terminal window, that I updated my branch from origin master and that brought in the updated ncbitaxon_terms.txt file. But when I am in Protege, it does not recognize this ID.

```
~/repos/go-ontology(master) $ git branch -l
  kinetoplastidCiliaryComponents-14713
* master
~/repos/go-ontology(master) $ git checkout kinetoplastidCiliaryComponents-14713 
Switched to branch 'kinetoplastidCiliaryComponents-14713'
~/repos/go-ontology(kinetoplastidCiliaryComponents-14713) $ git pull origin master 
From https://github.com/geneontology/go-ontology
 * branch            master     -> FETCH_HEAD
Updating 1a77032..b002bed
Fast-forward
 src/ontology/go-edit.obo                 | 1 -
 src/ontology/imports/ncbitaxon_terms.txt | 1 +
 2 files changed, 1 insertion(+), 1 deletion(-)
~/repos/go-ontology(kinetoplastidCiliaryComponents-14713) $ more src/ontology/imports/ncbitaxon_terms.txt 
NCBITaxon:9606
NCBITaxon:6073 ## Cnidaria
NCBITaxon:5653 ## Kinetoplastida
~/repos/go-ontology(kinetoplastidCiliaryComponents-14713) $ 
```

**Comment by krchristie** [comment]
@ukemi - Here is the ticket that is affected by not being able to use the taxon Kinetoplastida for taxon constraints for new terms I have already added. Note that in the text that I copied from my terminal window above, when I used the 'more' command to read the updated ncbitaxon_terms.txt file, only the line with Kinetoplastida is a new line; the other two lines were the contents of the file before I edited it. 

Here are the instructions I was following:
http://go-ontology.readthedocs.io/en/latest/AddTermToImport.html

This is the taxon I need to use:
NCBITaxon:5653 ## Kinetoplastida

**Comment by ukemi** [comment]
Hi @krchristie . It looks like you did everything correctly, but the term has not been incorporated into ncbitaxon_import.owl yet. I'm trying to figure out if building that file is supposed to be automatic or if it needs to be triggered.

**Comment by krchristie** [comment]
Thanks for looking into this @ukemi . I was wondering if it was something like that, so I checked again this morning if it worked now after giving it more time. However, it has now been almost a week since I added the term to the ncbitaxon_terms.txt file.

**Comment by krchristie** [comment]
@ukemi @cmungall - It's been over a month since the last time I tried, and I still can NOT use the taxon I need:  NCBITaxon:5653 ## Kinetoplastida

**Comment by balhoff** [comment]
@krchristie how does this look? #14930

**Comment by krchristie** [comment]
@balhoff - The diff in  #14930 looks like what I need, but even after using the command 
`git pull origin master` in my local master branch, this taxon is not available to me. It doesn't look like this command is pulling in the updates shown in your ticket present in the `src/ontology/imports/ncbitaxon_import.obo` or `src/ontology/imports/ncbitaxon_import.owl` files. I would have thought it should have. Is there something else I need to be doing?

You can see in this listing of the files in my imports directory that the two ncbitaxon_import files still have October dates:
<pre>
~/repos/go-ontology(master) $ ll src/ontology/imports/
total 57104
drwxr-xr-x  47 krc  1088672553     1598 Jan 25 09:39 .
drwxr-xr-x  30 krc  1088672553     1020 Jan 25 13:34 ..
-rw-r--r--   1 krc  1088672553      638 Jul 18  2017 caro_import.obo
-rw-r--r--   1 krc  1088672553     3515 Jul 18  2017 caro_import.owl
-rw-r--r--   1 krc  1088672553   971376 Jan 25 09:39 chebi_import.obo
-rw-r--r--   1 krc  1088672553  7954324 Jan 25 09:39 chebi_import.owl
-rw-r--r--   1 krc  1088672553    53928 Feb 22  2017 chebi_roles.owl
-rw-r--r--   1 krc  1088672553      652 Dec 11 10:49 chebi_terms.txt
-rw-r--r--   1 krc  1088672553   166363 Jun 16  2017 cl_import.obo
-rw-r--r--   1 krc  1088672553   445715 Jun 16  2017 cl_import.owl
-rw-r--r--   1 krc  1088672553      411 Sep  5 07:44 cl_terms.txt
-rw-r--r--   1 krc  1088672553     4470 Jun 16  2017 ddanat_import.obo
-rw-r--r--   1 krc  1088672553    15908 Jun 16  2017 ddanat_import.owl
-rw-r--r--   1 krc  1088672553       15 Jun 16  2017 ddanat_terms.txt
-rw-r--r--   1 krc  1088672553     7013 Jun 16  2017 fao_import.obo
-rw-r--r--   1 krc  1088672553    22960 Jun 16  2017 fao_import.owl
-rw-r--r--   1 krc  1088672553      347 Feb 22  2017 fao_terms.txt
-rw-r--r--   1 krc  1088672553    15510 Jul  7  2017 go-taxon-groupings-edit.owl
-rw-r--r--   1 krc  1088672553  1252824 Jul  7  2017 go-taxon-groupings.obo
-rw-r--r--   1 krc  1088672553  3590117 Jul  7  2017 go-taxon-groupings.owl
-rw-r--r--   1 krc  1088672553    30641 Oct 19 10:05 ncbitaxon_import.obo
-rw-r--r--   1 krc  1088672553   153683 Oct 19 10:05 ncbitaxon_import.owl
-rw-r--r--   1 krc  1088672553       75 Dec 12 15:34 ncbitaxon_terms.txt
-rw-r--r--   1 krc  1088672553    24709 Jun 16  2017 oba_import.obo
-rw-r--r--   1 krc  1088672553    82171 Jun 16  2017 oba_import.owl
-rw-r--r--   1 krc  1088672553      347 Feb 22  2017 oba_terms.txt
-rw-r--r--   1 krc  1088672553     5775 Jun 16  2017 pato_import.obo
-rw-r--r--   1 krc  1088672553    19593 Jun 16  2017 pato_import.owl
-rw-r--r--   1 krc  1088672553      347 Feb 22  2017 pato_terms.txt
-rw-r--r--   1 krc  1088672553   126269 Jun 16  2017 po_import.obo
-rw-r--r--   1 krc  1088672553   388185 Jun 16  2017 po_import.owl
-rw-r--r--   1 krc  1088672553      347 Feb 22  2017 po_terms.txt
-rw-r--r--   1 krc  1088672553   513154 Jun 16  2017 pr_import.owl
-rw-r--r--   1 krc  1088672553      347 Feb 22  2017 pr_terms.txt
-rw-r--r--   1 krc  1088672553    58583 Jan 25 09:39 ro_import.obo
-rw-r--r--   1 krc  1088672553   228574 Jan 25 09:39 ro_import.owl
-rw-r--r--   1 krc  1088672553    16845 Feb 22  2017 ro_pending.owl
-rw-r--r--   1 krc  1088672553      509 Oct  3 11:05 ro_terms.txt
-rw-r--r--   1 krc  1088672553    22692 Jun 16  2017 so_import.obo
-rw-r--r--   1 krc  1088672553    72621 Jun 16  2017 so_import.owl
-rw-r--r--   1 krc  1088672553      347 Feb 22  2017 so_terms.txt
-rw-r--r--   1 krc  1088672553   135908 Dec  1 09:20 substance_by_role.owl
-rw-r--r--   1 krc  1088672553  2765828 Nov  6 07:20 uberon_import.obo
-rw-r--r--   1 krc  1088672553  9942173 Nov  6 07:20 uberon_import.owl
-rw-r--r--   1 krc  1088672553      330 Aug 18 21:12 uberon_terms.txt
-rw-r--r--   1 krc  1088672553      330 Aug 15 09:58 uberon_terms.txt~
-rw-r--r--   1 krc  1088672553    27752 Jul 18  2017 x-disjoint.owl
</pre>

**Comment by balhoff** [comment]
Oh, sorry, hadn't merged yet. Should work now.

**Comment by krchristie** [comment]
Well, my ncbitaxon_import files have now updated, and I can see the new term for Kinetoplastida when I load the file into emacs

```
~/repos/go-ontology(master) $ git pull origin master 
remote: Counting objects: 41, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 41 (delta 29), reused 23 (delta 18), pack-reused 1
Unpacking objects: 100% (41/41), done.
From https://github.com/geneontology/go-ontology
 * branch            master     -> FETCH_HEAD
   022c40c..656de1e  master     -> origin/master
Updating 022c40c..656de1e
Fast-forward
 src/ontology/go-edit.obo                  |  40 +++++++++++++++++++--------------
 src/ontology/imports/ncbitaxon_import.obo |  12 +++++++++-
 src/ontology/imports/ncbitaxon_import.owl | 107 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----
 3 files changed, 137 insertions(+), 22 deletions(-)
```

but, I still can't use this term in Protege.

It doesn't come up in the autocomplete, and even if I type in either Kinetoplastida or its NCBI taxon ID, OR copy it from the emacs window and paste it into Protege to avoid spelling errors, Protege does not recognize the term and allow me to use it.

![img_8065](https://user-images.githubusercontent.com/10533218/35461990-ffdf1512-029e-11e8-88d5-6d0832d40c09.JPG)
![img_8066](https://user-images.githubusercontent.com/10533218/35461991-000badde-029f-11e8-8c41-052430abd2d3.JPG)

**Comment by balhoff** [comment]
I see this too, I don't understand. I you view only the ncbitaxon_import file you can find it in there. But it doesn't appear when you view GO.

**Comment by balhoff** [comment]
@krchristie please update and try again. I think it should work.
