### ISSUE TITLE
Jenkins diff job build failing

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15807]
Hello, 

The build has been failing 
https://build.berkeleybop.org/job/build-go-ontology/1895/console

It looks to me like the imports are refering to obsolete classes (thyroid hormone is a 'protein complex' GO:0043243). What do we nee to do ? 

@balhoff @cmungall @ukemi 

Thanks, Pascale

**Comment by balhoff** [comment]
@cmungall what do you think about adding in a `robot repair` invocation to the imports creation targets?

**Comment by cmungall** [comment]
Yes that's a good idea

Note though that this is not a fatal error. The actual error is caused in this part of the Makefile

```
go_inferences.owl: go-edit_noinf.obo
	$(ROBOT) reason -i $< -r ELK -n true -a true -x true annotate -R -O $(OBO)/go/imports/go_inferences.owl -o $@.tmp.owl && mv $@.tmp.owl $@
```

this is not invoked by travis, as this is part of the workflow for making the ontology diffs which runs on Jenkins (for various reasons we don't need to go into here).

It looks like there may have been an upstream change in the robot code, the `annotate -R -O` command *should* work.

Here is what needs to be done

 1. (incidental) figure out the cause of the reference violation, even though it's not at the heart of the issue. Looks like there is a stale PRO axiom in an import. These will be fixed by Jim's component strategy
 2. Report bug to robot tracker
 3. Implement workaround in Makefile if robot can't be fixed quickly

**Comment by cmungall** [comment]
aha, Becky made this change to robot 17 days ago:

https://github.com/ontodev/robot/commit/7311fab5843cc2918743a5d73edd22c69a7f792e

This made the `-R` option with other boolean options in robot (you pass an explicit true/false), but had the side-effect of breaking this. Will fix the makefile.

**Comment by balhoff** [comment]
I merged @cmungall's PR for the makefile and restarted the build. But now there is a different error:

```
Exception in thread "main" java.lang.NullPointerException
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.translateShorthandIdToExpandedId(OWLAPIObo2Owl.java:1766)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI_load(OWLAPIObo2Owl.java:1705)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI(OWLAPIObo2Owl.java:1670)
	at org.obolibrary.oboformat.writer.OBOFormatWriter$OWLOntologyNameProvider.getName(OBOFormatWriter.java:1182)
	at org.semanticweb.owlapi.oboformat.OBOFormatRenderer$1.getName(OBOFormatRenderer.java:74)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:637)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:363)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:203)
	at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:88)
	at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
	at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:155)
	at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:119)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1521)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1498)
	at owltools.io.ParserWrapper.saveOWL(ParserWrapper.java:289)
	at owltools.io.ParserWrapper.saveOWL(ParserWrapper.java:209)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:3549)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
Makefile:458: recipe for target 'go_inferences.obo' failed
```

**Comment by cmungall** [comment]
@balhoff can you recall when you regenerated chebi_import.owl 9 days ago did you do anything unusual?

This commit
eed581c3f0c751a8766a44553374ccd9d230d617

Somehow there was a blank node inserted into one of the GCIs, this results in a semi-silent OWL parse error (it warns on the command line and creates an Error1 class). This has a knock-on effect when trying to convert the ontology to obo, where it fails.

Pretty weird and obscure, should hopefully be fixed with my latest PR...

**Comment by pgaudet** [comment]
The ontology still isn't being built  - I cannot see changes I made - for example #15796 

Thanks, Pascale

**Comment by balhoff** [comment]
@cmungall no I didn't do anything unusual. I looked at the diffs for each of the rebuilt imports, and the CHEBI one had a fairly large number of changes. But I built the imports just using the basic `make` targets. However, that CHEBI import change was only merged yesterday, since @ukemi asked about its status. Should we roll it back?

**Comment by pgaudet** [comment]
Thanks @balhoff 
Just so I know what to expect, changes will only be visible in AmiGO after the next release, right ? 

Thanks, Pascale

**Comment by ukemi** [comment]
@cmungall. I looked at the obo diff yesterday when I was talking to @balhoff and only noticed my change and a bunch of label changes for GOCHE roles. I didn't notice any identifiers changing, so I thought it was safe to go ahead and merge.

**Comment by cmungall** [comment]
This ticket can be closed. This ticket is about the Jenkins reasoner diff job, which is now running successfully again.

@pgaudet - correct. Your changes are only visible in amigo after there is an amigo release. Note the release runs independent of the diff job, which is a standalone independent service.
