### ISSUE TITLE
37 invalid ISBN cross-references in the latest release

### ISSUE THREAD

**Issue by althonos** [geneontology/go-ontology#17190]
Hi there!

Great thing about ISBN is that they are not simply identifiers but also error correction codes. That makes it super easy to check the validity of a given ISBN, without having to actually query a centralized database.

Out of the 249 *unique* ISBNs contained in the latest (downloaded April 25) OBO file, 37 are invalid (some are just truncated, probably a copy-pasting error; some have a lowercase `x` although an uppercase `X` is expected; I didn't check all of them). The full list can be found below:

- [x]  ISBN:0185316194 -> ISBN:0815316194
- [x]  ISBN:047142520 -> ISBN:0943088399 (Biochemistry & Molecular Biology of Plants)
- [x]  ISBN:078173514 -> ISBN:0781735149
- [x] ISBN:08795694238 -> ISBN:0879694238
- [x]  ISBN:124925502 -> ISBN:0716720094 (Stryer)
-  [x] ISBN:019859951 -> PMID:26794871
- [x] ISBN:0943883999 -> ISBN:0943088399 (Biochemistry & Molecular Biology of Plants)
- [x]  ISBN:311011625
- [x] ISBN:00943088399 > ISBN:0943088399
-  [x] ISBN:01928006X -> ISBN:0192800981 (oxford dictionary of science); eating behavior: PMID:19361967
-  [x] ISBN:0080374903 ????  removed 1 (had other references); changed the other to GOC:dhl
-  [x] ISBN:0716020094 -> ISBN:0716720094
-  [x] ISBN:155581075X -> ? removed (had another reference)
-  [x] ISBN:006501037 -> ISBN:0943088399 (Biochemistry & Molecular Biology of Plants)
-  [x] ISBN:019854768
- [x] ISBN:08779694238 -> ISBN:0879694238
- [x] ISBN:01221146743 -> ISBN:0122146743
-   [x] ISBN:052131687 -> ISBN:0521316871
-  [x] ISBN:0781735140 -> ISBN:0781735149
- [x] ISBN:0-8249-3695-6 - > obsolete term- remove
- [x] ISBN:1-55581-073-x
- [x] ISBN:01950657191 -> ISBN:0195065719
-  [x] ISBN:052143641 -> ISBN:0521436125 
-   [x] ISBN:10615049 -> PMID:28774948
-  [x] ISBN:0051406910 -> ???? removed 1 (had other references)
-   [x] ISBN:014051403 -> ISBN:0140514031
-  [x] ISBN:0781802976 ->  ? change to GOC:jl
-   [x] ISBN:071672009 -> ISBN:0716720094
-   [x] ISBN:91191028X -> OK https://www.ebay.com/itm/The-Merck-Index-Eleventh-Edition-ISBN-91191028X-1989-/142046037467
-  [x] ISBN:0721601465 -> ISBN:9780721601465
-    [x] ISBN:10652251 -> PMID:21494665
-   [x] ISBN:087797099 ->ISBN:0877797099
-  [x] ISBN:0813516194  -> ISBN:0815316194
-  [x] ISBN:0683400078 -> ISBN:0838580343
-    [x] ISBN:96235764 -> Wikipedia:Myosin
-  [x] ISBN:0198596732 -> ISBN:0198506732
-  [x] ISBN:155581073x

**Comment by pgaudet** [comment]
Naive question: Is there any way we can find the correct reference? Or do we just remove the cross-references ? 

Pascale

**Comment by mah11** [comment]
> ISBN:0185316194

well, this one is a typo for ISBN:0815316194 .. but I only recognize it because the correct one is for a textbook that's been used for tons of defs!

**Comment by pgaudet** [comment]
That's impressive Midori !

**Comment by althonos** [comment]
@pgaudet : grepping the `go.obo` file helped for these:
- ISBN:071672009 is most likely ISBN:0716720094
- ISBN:311011625 is most likely ISBN:3110116251
- ISBN:019854768 is most likely ISBN:0198547684
- ISBN:014051403 is most likely ISBN:0140514031
- ISBN:078173514 is most likely ISBN:0781735149

For the other, the correct reference may be found with a bit of luck:
- searching for ISBN:01950657191 gives nothing, but googling ISBN:0195065719 gives the ID of `The Fine Structure of the Nervous System: Neurons and Their Supporting Cells`, which is probably the source (this is used in definition of neuron-related terms).
- searching for ISBN:052131687, it seems to be missing a trailing 1, which would give ISBN:0521316871 (`Algae: Introduction Phycology: An Introduction to Phycology`), for the definition of the `cyanelle` term

**Comment by althonos** [comment]
> OK https://www.ebay.com/itm/The-Merck-Index-Eleventh-Edition-ISBN-91191028X-1989-/142046037467
This one is OK in the sense that it resolves to an actual book, but should be zero-prefixed to reach 10 digits :wink:

**Comment by pgaudet** [comment]
Hi @althonos Hopefully this is now fixed. Let me know if you find other errors. 

Thanks, Pascale

**Comment by althonos** [comment]
Hi @pgaudet,
running my [validation tool](https://github.com/fastobo/fastobo-validator/releases) I still found some ISBNs that you forgot to fix in the `go-edit.obo` file:
- `ISBN:91191028X` (as said before requires a leading 0) [line 113121]
- `ISBN:155581073x` (should have an uppercase X) [line 528931]
- `ISBN:0-8249-3695-6` (it has not been removed from obsolete terms) [lines 500796 to 501002]
- `ISBN:071672009` [line 58578]
- `ISBN:01950657191` [lines 415578, 553166, 553201, 553259, 553271, 553283]
- `ISBN:078173514` [line 318113]
- `ISBN:052131687` [line 94669]
