### ISSUE TITLE
GO load failing due to a problem in the ontology

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/go-ontology#17584]
The GO ontology load is failing at ZFIN. It looks like it is due to an error in a specific term in the ontology: 
[java] Error: Attempted to specify obsolete value obsolete negative regulation of growth of symbiont in host for consider tag.
 [java] on line: 199542
 [java] charnum: -1
 [java] line: consider: GO:0044130

Note: This case might be related to this issue: https://github.com/INCATools/ontology-development-kit/issues/214

**Comment by balhoff** [comment]
@sabrinatoro which URL are you using to obtain GO?

**Comment by balhoff** [comment]
And which software do you use to parse the file?

**Comment by balhoff** [comment]
Ah, I see this issue in snapshot (June 28). But the Protégé OBO parser seems to load it anyway.

**Comment by sabrinatoro** [comment]
@balhoff :
This is what we use to parse the file: 
import org.obo.dataadapter.AbstractParseEngine;
import org.obo.dataadapter.DefaultOBOParser;
import org.obo.dataadapter.OBOParseEngine;
import org.obo.dataadapter.OBOParseException;

and this is the URL we use to get the file: 
http://purl.obolibrary.org/obo/go/snapshot/go.obo
obo-util.zip

**Comment by balhoff** [comment]
Thanks!  I believe the file is syntactically valid. Maybe we should add a SPARQL check to catch this situation in Travis. We currently check for `replaced_by`, but not `consider`: 

https://github.com/geneontology/go-ontology/blob/master/src/sparql/replacedby-obsolete-violation.sparql

**Comment by cmungall** [comment]
Yes, let's add the check

**Comment by balhoff** [comment]
Should be fixed in the next snapshot.

**Comment by hattrill** [comment]
Hi @balhoff - was the static release 2019-07-01 fixed?

**Comment by balhoff** [comment]
@hattrill no, this problem exists in the 2019-07-01 release. cc @pgaudet

**Comment by hattrill** [comment]
Not sure how our scheduled update this month will handle it. 
Just to be clear, the problem is one line - an obsolete GO id:

consider: GO:0044130

**Comment by balhoff** [comment]
It's a bit more than that. The reported line was just the first one encountered. I fixed several: 

https://github.com/geneontology/go-ontology/commit/db2ef67e85aa606c3569c6586d8de0b1aea7f76c

However the ones that I updated with a new ID were alt_ids rather than regular obsolete terms, and those apparently weren't causing problems. But you can see a few others that have no replacement.

**Comment by hattrill** [comment]
So, prob accummulated over sometime - hopefully won't make a difference to our load, but I will give our devs a heads-up over the one the tripped up ZFIN.
Thanks

**Comment by sabrinatoro** [comment]
@balhoff : The load is still failing. I cannot tell whether it is due to the same issue or not (there is no technical team in today). 
@hattrill : just the heads up.

**Comment by sabrinatoro** [comment]
The problem has been resolved! Thank you @balhoff !

**Comment by hdrabkin** [comment]
As of yesterday I no longer get GO Load Failure qc emails. Everything back to normal. I can close this
