### ISSUE TITLE
Obsolete term (GO:0044146) set as "consider:" for another obsolete term (GO:0075340)

### ISSUE THREAD

**Issue by julie-sullivan** [geneontology/go-ontology#17671]
Hello GO!

My software is generating an error because it doesn't expect the parameter `consider` to contain an obsolete term. 

Here we have one obsolete term (`GO:0075340`) with another obsolete term (`consider: GO:0044146`) as a replacement:

```
[Term]
id: GO:0075340
name: obsolete negative regulation of growth or development of symbiont during interaction with host
namespace: biological_process
def: "OBSOLETE. Any process that stops, prevents, or reduces the frequency, rate or extent of the increase in size or mass of an organism, or the progression of an organism from an initial condition to a later condition, occurring in, on or near the exterior of its host organism." [GOC:jl]
comment: This term was made obsolete because it contained a conjunction (or). It has been replaced with the terms 'negative regulation of development of symbiont during interaction with host ; GO:0044147' and 'negative regulation of growth of symbiont during interaction with host ; GO:0044146'.
synonym: "negative regulation of growth or development of symbiont during interaction with host" EXACT []
is_obsolete: true
consider: GO:0044146
consider: GO:0044147
```
Is this legal? or a mistake?

Thank you!! :)

**Comment by julie-sullivan** [comment]
GO:0044126 is also suggested for GO:0033665

```
[Term]
id: GO:0033665
name: obsolete regulation of growth or development of symbiont in host
namespace: biological_process
def: "OBSOLETE. Any process by which the symbiont regulates the increase in its size or mass, or its progression from an initial condition to a later condition, within the cells or tissues of the host organism. 
This may (but not necessarily) include a filamentous growth form, and also can include secretion of proteases and lipases to break down. The host is defined as the larger of the organisms involved in the symbiot
ic interaction." [GOC:dph, GOC:pamgo_curators, GOC:tb]
comment: This term was made obsolete because it contained a conjunction (or). It has been replaced with the terms 'regulation of development of symbiont in host ; GO:0044127' and 'regulation of growth of symbiont in host ; GO:0044126'.
synonym: "modulation of growth or development of organism within host" EXACT []
synonym: "modulation of growth or development of symbiont within host" EXACT [GOC:dph, GOC:tb]
synonym: "modulation of invasive growth" BROAD []
synonym: "regulation of growth or development of symbiont in host" EXACT []
synonym: "regulation of growth or development of symbiont within host" EXACT []
is_obsolete: true
consider: GO:0044126 <-- obsolete term
consider: GO:0044127
```

**Comment by ukemi** [comment]
I thought we had a check to disallow this.

**Comment by hattrill** [comment]
Relates directly to problem reported here #17584

**Comment by pgaudet** [comment]
Hi @julie-sullivan 
Where do you get the ontology from ? This looks like it was already fixed. 

Thanks, Pascale

**Comment by julie-sullivan** [comment]
Hi @pgaudet! Thanks for looking at this. No, it looks like the error is still there to me!

I downloaded `go-basic.obo` from here: http://geneontology.org/docs/download-ontology/

Then grepped for `GO:0044146`. You will see that even though that's an obsolete term, it's still tagged as "consider":

```
consider: GO:0044146 <-- obsolete
consider: GO:0044147
```
I assume the fix is going to propagate to this file eventually? :) Thanks!

**Comment by pgaudet** [comment]
Hi @julie-sullivan 
The file will be updated in the next GO release, which will probably be next week. 

Sorry about the delay. 

Pascale
