### ISSUE TITLE
Some terms have ended up without an asserted parent, after "part term" obsoletion

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#17804]
The script I used to obsolete part terms and refactor their asserted children ended up being confused by some situations where a term had two part terms as parents. This is causing the pipeline to break (we should set up Travis to check this!).

This will be fixed by #17799.

**Comment by balhoff** [comment]
Done.

**Comment by ukemi** [comment]
Thanks @balhoff!!! Although I still don't know why the ontology didn't get flagged as not being is_a complete in the checks. I know I have gotten this error before (or at least I dreamed it). @dougli1sqrd any ideas about this?

**Comment by ukemi** [comment]
It at least should have triggered the 'namespace not the same as parent' violation, right?

**Comment by dougli1sqrd** [comment]
So I see that $(SRC)-check runs:
```
../util/check-obo-for-standard-release.pl --disable-isa-incomplete --xref-abbs GO.xrf_abbs go-edit.obo > go-edit.obo-check
```

This runs with no errors.

But I see the release process runs `./util/check-obo-for-standard-release.pl` without the `disable-isa-incomplete` option. When I run this manually:
```
$ ../util/check-obo-for-standard-release.pl --xref-abbs GO.xrf_abbs go-edit.obo > go-edit.obo-check.tmp && mv go-edit.obo-check.tmp go-edit.obo-check
```
I get a torrent of errors like we see in the jenkins build:
```
  :: ERROR: isa-incomplete: GO:2001297
  :: ERROR: isa-incomplete: GO:2001298
  :: ERROR: isa-incomplete: GO:2001299
  :: ERROR: isa-incomplete: GO:2001300
  :: ERROR: isa-incomplete: GO:2001301
  :: ERROR: isa-incomplete: GO:2001302
  :: ERROR: isa-incomplete: GO:2001303
  :: ERROR: isa-incomplete: GO:2001304
  :: ERROR: isa-incomplete: GO:2001305
  :: ERROR: isa-incomplete: GO:2001306
  :: ERROR: isa-incomplete: GO:2001307
  :: ERROR: isa-incomplete: GO:2001311
  :: ERROR: isa-incomplete: GO:2001312
  :: ERROR: isa-incomplete: GO:2001313
  :: ERROR: isa-incomplete: GO:2001314
  :: ERROR: isa-incomplete: GO:2001315
  :: ERROR: isa-incomplete: GO:2001316
  :: ERROR: isa-incomplete: GO:2001317
... etc
```

Why should we turn this off in the $(SRC)-check recipe, and can we turn it on so we get this reflected in travis checks?

**Comment by balhoff** [comment]
It's okay for the edit file to be isa-incomplete, since the hierarchy needs to be inferred. So we would need to extend the travis build to go.obo, in order to check it like this.

**Comment by dougli1sqrd** [comment]
Could we just convert `reasoned.owl` into obo and then run the check? Or do we need to do the full release script run? (`$(ONT).obo` which includes ontology-release-runner)?

**Comment by ukemi** [comment]
But in the edit file, there always has to be at least one asserted superclass, whether it is in the equivalence axiom or is asserted as a subclass. Can't we take this constraint into account?

**Comment by balhoff** [comment]
That's true, I think the perl script just doesn't take that into account. We should get a SPARQL check in place for this. Honestly I thought we already did. @dougli1sqrd can you see if any of the SPARQL checks should be covering this?

**Comment by ukemi** [comment]
I'm almost certain that I have inadvertently made terms without is_a parents and got a Travis fail.

**Comment by dougli1sqrd** [comment]
@ukemi Do we have examples of what the current failure is vs what you described above, where the travis checks find your terms without is_a parent? 

@balhoff I can look at the sparql checks. Those would want to operate on reasoned.owl, yes? And what is the check exactly? Like the issue is that terms are not attached to one of the roots? Is that right?

**Comment by balhoff** [comment]
I think it is sufficient to check that each GO term except the roots is `rdfs:subClassOf` some GO term, in reasoned.owl.

**Comment by ukemi** [comment]
That will work.
