### ISSUE TITLE
GO terms with xref: EC:1.11.1 (peroxidases)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19196]
EC:1.11.1 is the grouping ID for 'peroxidases':
https://enzyme.expasy.org/EC/1.11.1.-

Three terms to review in the GO:

id: GO:0019806
name: bromide peroxidase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2 R-H + 2 bromide + hydrogen peroxide = 2 R-Br + 2 H2O. Enzymes with this activity often accept other halide ions as substrates, including chloride and iodide." [EC:1.11.1.10]
synonym: "bromoperoxidase activity" EXACT []
xref: EC:1.11.1

=> this EC should be replaced with EC 1.11.1.18 (https://enzyme.expasy.org/EC/1.11.1.18)

id: GO:0008379
name: thioredoxin peroxidase activity
namespace: molecular_function
alt_id: GO:0009031
def: "Catalysis of the reaction: thioredoxin + hydrogen peroxide = thioredoxin disulfide + H2O." [MetaCyc:RXN0-267]
synonym: "thiol peroxidase activity" EXACT []
synonym: "TPx activity" EXACT []
synonym: "TrxPx activity" EXACT []
xref: EC:1.11.1

=> this one should probably be removed (I can't easily see a specific EC to replace it)

id: GO:0004601
name: peroxidase activity
namespace: molecular_function
alt_id: GO:0016685
alt_id: GO:0016686
alt_id: GO:0016687
alt_id: GO:0016693
def: "Catalysis of the reaction: donor + hydrogen peroxide = oxidized donor + 2 H2O." [EC:1.11.1.7, RHEA:56136]
subset: goslim_metagenomics
synonym: "bacterial catalase-peroxidase activity" NARROW []
synonym: "donor:hydrogen-peroxide oxidoreductase activity" EXACT [EC:1.11.1.7]
synonym: "eosinophil peroxidase activity" NARROW []
synonym: "extensin peroxidase" NARROW [EC:1.11.1.7]
synonym: "guaiacol peroxidase" NARROW [EC:1.11.1.7]
synonym: "heme peroxidase" NARROW [EC:1.11.1.7]
synonym: "horseradish peroxidase (HRP)" NARROW [EC:1.11.1.7]
synonym: "japanese radish peroxidase" NARROW [EC:1.11.1.7]
synonym: "lactoperoxidase activity" NARROW []
synonym: "MPO" RELATED [EC:1.11.1.7]
synonym: "myeloperoxidase activity" NARROW []
synonym: "oxyperoxidase activity" EXACT [EC:1.11.1.7]
synonym: "peroxidase reaction" EXACT []
synonym: "protoheme peroxidase" NARROW [EC:1.11.1.7]
synonym: "pyrocatechol peroxidase" NARROW [EC:1.11.1.7]
synonym: "scopoletin peroxidase" NARROW [EC:1.11.1.7]
synonym: "secretory plant peroxidase activity" NARROW []
synonym: "thiocyanate peroxidase" NARROW [EC:1.11.1.7]
synonym: "verdoperoxidase" NARROW [EC:1.11.1.7]
xref: EC:1.11.1.7

=> this one has EC:1.11.1.7 as an xref, but it's the parent term for various other peroxidase terms in the GO, so I wonder whether EC:1.11.1 is more appropriate?

It's a bit odd because EC:1.11.1.7 is called 'peroxidase' in the EC, with this definition:
2 phenolic donor + H(2)O(2) <=> 2 phenoxyl radical of the donor + 2 H(2)O
https://enzyme.expasy.org/EC/1.11.1.7

Compare this to the GO def for "peroxidase activity" above:
"Catalysis of the reaction: donor + hydrogen peroxide = oxidized donor + 2 H2O."

Maybe a new grouping term is required here to resolve this discrepancy? What do you think? (if so, I can make a new ticket.)

**Comment by pgaudet** [comment]
EC:1.11.1.7 doesn't have so many synonyms 

 https://enzyme.expasy.org/EC/1.11.1.7

Was this split at some point ?

**Comment by hdrabkin** [comment]
Perhaps whoever made the term at the time added the synonyms. It also looks like some of the synonyms are gene or gene product names (japanese radish peroxidase).
I would /will remove the EC xref from anything that EC doesn't have.
I

**Comment by pgaudet** [comment]
You can probably remove some of the gene product names as synonyms - I'm not sure those are very useful. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
We really don't know WHAT people search for when they search GO!

**Comment by pgaudet** [comment]
Still - those are more like annotations. We can not add all gene products that apply to a term as synonym. It's not scalable and messy - dont you think ?

**Comment by hdrabkin** [comment]
NOT suggested we do;

**Comment by sjm41** [comment]
But the key question here is whether GO:0004601 (peroxidase activity) is meant to correspond to:
(i) EC:1.11.1 (the grouping term for peroxidases in EC), which is suggested by its GO definition and position in the GO hierarchy/children
(ii) EC:1.11.1.7 (a specific term for 'peroxidase'/'Lactoperoxidase' in EC), which is suggested by its current xref and synonyms - though the GO def doesn't seem to quite match the EC def.

It looks like GO:0004601 is currently trying to be both (i) and (ii), and I'm not sure that's right?

**Comment by hdrabkin** [comment]
The EC 1.11.1.17 maps to this
2 phenolic donor + H(2)O(2) <=> 2 phenoxyl radical of the donor + 2 H(2)O
The RHEA RHEA:56136  is this
RHEA:56136          (APPROVED)
2 a phenolic donor + H2O2 = 2 a phenolic radical donor + 2 H2O 
Glad to see they agree
BUt, as you note,The GO def is
catalysis of the reaction: donor + hydrogen peroxide = oxidized donor + 2 H2O; 
So do ALL peroxidases use a phenolic donor? My guess is no

@deustp01 can you lend me your thoughts

**Comment by ValWood** [comment]
These synonyms will probably be useful for searching for  activities because historically they were used as proxies for specific activities. I think we should follow Rhea/Brenda here and include if they do.

**Comment by hdrabkin** [comment]
yes @ValWood , I just won't attribute them to that EC number; RHEA does not do synonyms.
And EC does not do them either; they to 'alternative names' and do not make assumptions about exact/related/ etc. That is a GO thing.

**Comment by hdrabkin** [comment]
Requesting RHEA for EC:1.11.1.18; removed partial ec
Requesting RHEA for thioredoxin peroxidase; removed partial ec.

**Comment by hdrabkin** [comment]
requested RHEA  for EC:1.11.10 and EC:1.11.18, Chloride and Bromide respectively.

**Comment by hdrabkin** [comment]
Requested RHEA for GO:0008379, Rhea ticket 183264

**Comment by pgaudet** [comment]
Ready ?

**Comment by hdrabkin** [comment]
Rhea for EC:1.11.1.18 is not available. 

GO:0008379, based on Metacyc xref should be EC:1.11.1.15 but no RHEA yet
Tracking 183264 now.

**Comment by hdrabkin** [comment]
Found: put in wrong folder
 RHEA:63528  for GO:0008379
[thioredoxin]-dithiol + H2O2 = [thioredoxin]-disulfide + 2 H2O
RHEA:63528 will be publicly available mid-June.
FYI, according to table I of PMID:11087748, I'm going to create 2 additional
reactions, one for ter-butyl hydroperoxide (CHEBI:64090) and one for cumene
hydroperoxide (CHEBI:78673)

**Comment by hdrabkin** [comment]
added RHEA

**Comment by hdrabkin** [comment]
Removed EC:1.11.1.17 and RHEA to grouping term GO:0004601; removed all EC:1.11.1.17 xrefs in synonyms, etc. to this term. It is a generic grouping term for all of the other peroxidases. 
Searching for where these requests ended up
GO:0019806, EC:1.11.18
PMID:22842973
RH + HBr + H(2)O(2) <=> RBr + 2 H(2)O

This parallels EC:1.11.1.10, PMID:8344520
GO:0016691
RH + Cl(-) + H(2)O(2) <=> RCl + 2 H(2)O

**Comment by sjm41** [comment]
@harold Did you ever get the new RHEAs you requested above (back in 2020)? If they are not forthcoming, I suggest we close this ticket (my original request has been addressed).

**Comment by hdrabkin** [comment]
EC:1.11.1.18 still does not have a RHEA. So let's close this.

**Comment by harold** [comment]
@harold checking in here - good luck with your computation biology project! 😄
