### ISSUE TITLE
handling xref type annotations in go.obo and go.owl

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#20770]
To deal with problems caused by migrating xrefs from merged or obsoleted terms (as in #20135) we added axiom annotations to xrefs for cases where they can be called `skos:narrowMatch`. However I'm getting a bit confused about how to proceed with incorporating them into the go.obo/owl release files. The current release pipeline filters out "trailing qualifiers", and thus these annotations are dropped, bringing us back to the problem we were trying to fix (excessive xrefs).

A trailing qualifier would look like this (`{source="skos:narrowMatch"}`):

```
[Term]
id: GO:0004222
name: metalloendopeptidase activity
namespace: molecular_function
def: "Catalysis of the hydrolysis of internal, alpha-peptide bonds in a polypeptide chain by a mechanism in which water acts as a nucleophile, one or two metal ions hold the water molecule in place, and charged amino acid side chains are ligands for the metal ions." [GOC:mah, https://www.ebi.ac.uk/merops/about/glossary.shtml#CATTYPE, https://www.ebi.ac.uk/merops/about/glossary.shtml#ENDOPEPTIDASE]
synonym: "metalloendoprotease activity" NARROW [GOC:mah]
synonym: "metalloendoproteinase activity" NARROW [GOC:mah]
xref: EC:3.4.24.-
xref: EC:3.4.24.11 {source="skos:narrowMatch"}
```

Right now trailing qualifiers are stripped so that those xrefs for that term end up looking like this:

```
xref: EC:3.4.24.-
xref: EC:3.4.24.11
```

Issues to weigh:
- Including the trailing qualifiers in go.obo and go.owl would allow @sjm41 to filter out narrow xrefs
- Including the trailing qualifiers in go.obo and go.owl could be a parsing problem for a lot of unsuspecting users
- Completely filtering xrefs which have narrowMatch qualifiers before writing go.obo would be just as good for @sjm41 
- Completely filtering xrefs which have narrowMatch qualifiers would make them disappear from ec2go, which @cmungall does not want to happen
- We could change the ec2go generation command to use a different GO file instead of go.obo (i.e. from an earlier stage in the build), so that all mappings are included

It's hard for me to gauge how big of an issue it might be for downstream parsers to suddenly start including trailing qualifiers. Maybe the best solution for the moment is to filter narrowMatch xrefs before writing go.obo, and also update the ec2go generator to run before that filtering happens.

**Comment by sjm41** [comment]
_Maybe the best solution for the moment is to filter narrowMatch xrefs before writing go.obo, and also update the ec2go generator to run before that filtering happens._
This sounds good to me.

**Comment by pgaudet** [comment]
@cmungall What do you think ? 
@thomaspd and I agree with making go.obo simpler. 

We should also look into fixing the ec2GO file (see eg http://release.geneontology.org/2021-01-01/ontology/external2go/ec2go): probably NARROW and EXACT synonyms are OK; but we may not want to include BROAD synonyms for mappings. 

Thanks, Pascale

**Comment by balhoff** [comment]
Thanks all, I implemented filtering out of narrow xrefs, after mapping files are generated, in #20783.

**Comment by sjm41** [comment]
Hi @balhoff
I just saw that the Feb 2021 GO release was available and looked at go-basic.obo dated 2021-02-01.
The additional (narrow) EC xrefs are still present - i.e. same issue as first reported in #20135.
Did this fix miss the Feb release?  Will it now be in the March release?
Thanks,
Steven.

**Comment by pgaudet** [comment]
Hi @sjm41 

Indeed this change just missed the release. It will be in the next one. 

Thanks, Pascale

**Comment by sjm41** [comment]
OK, Thanks @pgaudet .
FYI @hattrill

**Comment by balhoff** [comment]
@sjm41 sorry to miss the release this time—but we do have a chance now to make sure everything in the snapshots looks correct. A new snapshot has not yet been produced since this change was made; I see the latest as 2021-02-02. I'll try to note when a new one appears.

**Comment by sjm41** [comment]
Hi @balhoff.  I just looked at the go-basic.obo dated 2021-02-08, and the EC xrefs now look good!

Looking at the seven problem terms I originally listed in #20135, all are now 'fixed' in that they now have only a single EC xref:

id: GO:0004222
name: metalloendopeptidase activity
xref: EC:3.4.24.-

id: GO:0004252
name: serine-type endopeptidase activity
xref: EC:3.4.21.-

id: GO:0004197
name: cysteine-type endopeptidase activity
xref: EC:3.4.22.-

id: GO:0004190
name: aspartic-type endopeptidase activity
xref: EC:3.4.23.-

id: GO:0004185
name: serine-type carboxypeptidase activity
xref: EC:3.4.16.-

id: GO:0004181
name: metallocarboxypeptidase activity
xref: EC:3.4.17.-

id: GO:0004177
name: aminopeptidase activity
xref: EC:3.4.11.-

I'm happy! :-)

(I see these seven cases all still have multiple Reactome xrefs (e.g. GO:0004222 has 93), but maybe that's expected and fine - and that won't cause any issues with FlyBase processing pipelines anyway...)

**Comment by balhoff** [comment]
@sjm41 great, thank you for being patient! We haven't started applying the scopes to other xref types, but I expect we will soon.
