### ISSUE TITLE
Missing parent:  kinase regulator activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21448]
GO:0019207 | kinase regulator activity
is not a descendant of 
GO:0098772 | molecular function regulator |  

<img width="359" alt="Screenshot 2021-05-14 at 19 47 35" src="https://user-images.githubusercontent.com/7359272/118315384-5e766b80-b4ed-11eb-8d86-dc7c13406322.png">

Affecting slims.

**Comment by pgaudet** [comment]
Thanks for pointing this out. Many regulator functions used 'molecular_function' as a genera rather than 'molecular function regulator', this was classifying them incorrectly. 

Fixed the terms highlighted below:


<img width="471" alt="image" src="https://user-images.githubusercontent.com/4782928/118463766-6fe39180-b700-11eb-86fa-df6c8f10da3c.png">

**Comment by ValWood** [comment]
I'm not sure, but I think some change here has brought back the relationship between "kinase activity and "enzyme regulator activity"

this query was zero:
zero (enzyme inhibitor activity (GO:0004857) OR enzyme activator activity (GO:0008047)) AND protein kinase activity (GO:0004672)

but is now 3

**Comment by ValWood** [comment]
OK, it is because 

cyclin-dependent protein kinase activating kinase activity
still exists

so once 
https://github.com/geneontology/go-ontology/issues/20884
is done, this intersection will disappear again
