### ISSUE TITLE
Latest obo file throws an error during parsing

### ISSUE THREAD

**Issue by cmpich** [geneontology/go-ontology#27263]
the latest GO file throws the following error when trying to parse it with obo.jar

` ERROR - Error while parsing Obo file
     [java] org.obo.dataadapter.OBOParseException: Undefined category goc.
     [java] 	at org.obo.dataadapter.OBOParseEngine.translateException(OBOParseEngine.java:1456) ~[obo.jar:1.000]
     [java] 	at org.obo.dataadapter.OBOParseEngine.translateAndThrow(OBOParseEngine.java:1448) ~[obo.jar:1.000]
     [java] 	at org.obo.dataadapter.OBOParseEngine.doParse(OBOParseEngine.java:410) ~[obo.jar:1.000]
     [java] 	at org.obo.dataadapter.AbstractParseEngine.parse(AbstractParseEngine.java:48) ~[obo.jar:1.000]
     [java] 	at org.obo.dataadapter.AbstractParseEngine.parse(AbstractParseEngine.java:72) ~[obo.jar:1.000]
     [java] 	at org.zfin.ontology.datatransfer.service.LoadOntology.createOboSession(LoadOntology.java:1112) ~[classes/:?]
     [java] 	at org.zfin.ontology.datatransfer.service.LoadOntology.initialize(LoadOntology.java:333) [classes/:?]
     [java] 	at org.zfin.ontology.datatransfer.service.LoadOntology.initialize(LoadOntology.java:321) [classes/:?]
     [java] 	at org.zfin.ontology.datatransfer.service.LoadOntology.main(LoadOntology.java:175) [classes/:?]
     [java] ERROR - Error during Ontology Load
     [java] java.lang.RuntimeException: Error: Undefined category goc.`

The file header looks like this:
`format-version: 1.2
data-version: releases/2024-02-22
subsetdef: chebi_ph7_3 "Rhea list of ChEBI terms representing the major species at pH 7.3."
subsetdef: gocheck_do_not_annotate "Term not to be used for direct annotation"
subsetdef: gocheck_do_not_manually_annotate "Term not to be used for direct manual annotation"
subsetdef: goslim_agr "AGR slim"
subsetdef: goslim_aspergillus "Aspergillus GO slim"
subsetdef: goslim_candida "Candida GO slim"
subsetdef: goslim_chembl "ChEMBL protein targets summary"
subsetdef: goslim_drosophila "Drosophila GO slim"
subsetdef: goslim_flybase_ribbon "Insecta GO ribbon slim"
subsetdef: goslim_generic "Generic GO slim"
subsetdef: goslim_metagenomics "Metagenomics GO slim"
subsetdef: goslim_mouse "Mouse GO slim"
subsetdef: goslim_pir "PIR GO slim"
subsetdef: goslim_plant "Plant GO slim"
subsetdef: goslim_pombe "Fission yeast GO slim"
subsetdef: goslim_prokaryote "GO subset for prokaryotes"
subsetdef: goslim_prokaryote_ribbon "Prokaryote GO ribbon slim"
subsetdef: goslim_synapse "synapse GO slim"
subsetdef: goslim_yeast "Yeast GO slim"
synonymtypedef: syngo_official_label "label approved by the SynGO project"
synonymtypedef: systematic_synonym "Systematic synonym" EXACT
default-namespace: gene_ontology
ontology: go
property_value: has_ontology_root_term GO:0003674
property_value: has_ontology_root_term GO:0005575
property_value: has_ontology_root_term GO:0008150
property_value: http://purl.org/dc/elements/1.1/description "The Gene Ontology (GO) provides a framework and set of concepts for describing the functions of gene products from all organisms." xsd:string
property_value: http://purl.org/dc/elements/1.1/title "Gene Ontology" xsd:string
property_value: http://purl.org/dc/terms/license http://creativecommons.org/licenses/by/4.0/
property_value: owl:versionInfo "2024-02-22" xsd:string
`

**Comment by pgaudet** [comment]
Thanks for reporting this. Hopefully this is now fixed.

**Comment by cmpich** [comment]
I am still seeing the same issue. Downloading from the following purl:
http://purl.obolibrary.org/obo/go/snapshot/go.obo

**Comment by balhoff** [comment]
We haven't had a new snapshot release yet. They have been slow lately; we're hoping to be able to increase the frequency soon.

**Comment by cmpich** [comment]
The latest file now creates this error:
`    [java] charnum: -1
     [java] line: subset: do_not_annotate
     [java] 	at org.obo.dataadapter.DefaultOBOParser.readSubset(DefaultOBOParser.java:889)
     [java] 	at org.obo.dataadapter.OBOParseEngine.parseTagValue(OBOParseEngine.java:647)
     [java] 	at org.obo.dataadapter.OBOParseEngine.parseTag(OBOParseEngine.java:996)
     [java] 	at org.obo.dataadapter.OBOParseEngine.doParse(OBOParseEngine.java:406)
     [java] 	at org.obo.dataadapter.AbstractParseEngine.parse(AbstractParseEngine.java:48)
     [java] 	at org.obo.dataadapter.AbstractParseEngine.parse(AbstractParseEngine.java:72)
     [java] 	at org.zfin.ontology.datatransfer.service.LoadOntology.createOboSession(LoadOntology.java:1112)
     [java] 	at org.zfin.ontology.datatransfer.service.LoadOntology.initialize(LoadOntology.java:333)
     [java] 	at org.zfin.ontology.datatransfer.service.LoadOntology.initialize(LoadOntology.java:321)
     [java] 	at org.zfin.ontology.datatransfer.service.LoadOntology.main(LoadOntology.java:175)
     [java] ERROR - Error while parsing Obo file
     [java] org.obo.dataadapter.OBOParseException: Undefined category do_not_annotate.`

**Comment by cmpich** [comment]
When Will I be able to see this fix?

**Comment by balhoff** [comment]
Snapshot production has been a bit sporadic recently due to some pipeline issues, but I know that @kltm is working to get one out now. Hopefully very soon.

**Comment by balhoff** [comment]
@cmpich a new snapshot is available.

**Comment by balhoff** [comment]
@cmpich FYI due to a release timing mishap, one of these problems snuck into the last official release. I created a CI check, but it went in after the release. I think we will create another release ASAP. Not sure if that will impact you, but sorry about these issues!
